apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensor.fullname" . }}
  labels:
    {{- include "sensor.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "sensor.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}