const ALERT_TYPE = {
  BUTTONS_NOT_URGENT: 'BUTTONS_NOT_URGENT',
  BUTTONS_URGENT: 'BUTTONS_URGENT',
  SENSOR_STILLNESS: 'SENSOR_STILLNESS',
  SENSOR_DURATION: 'SENSOR_DURATION',
  SENSOR_UNKNOWN: 'SENSOR_UNKNOWN',
}

module.exports = Object.freeze(ALERT_TYPE)
