const CHATBOT_STATE = {
  STARTED: 'STARTED',
  WAITING_FOR_REPLY: 'WAITING_FOR_REPLY',
  RESPONDING: 'RESPONDING',
  WAITING_FOR_CATEGORY: 'WAITING_FOR_CATEGORY',
  COMPLETED: 'COMPLETED',
  RESET: 'RESET',
}

module.exports = Object.freeze(CHATBOT_STATE)
