const EVENT_TYPE = {
  DURATION_ALERT: 'DURATION_ALERT',
  STILLNESS_ALERT: 'STILLNESS_ALERT',
  DOOR_OPENED: 'DOOR_OPENED',
  MSG_SENT: 'MSG_SENT',
  MSG_RECEIVED: 'MSG_RECEIVED',
}

module.exports = Object.freeze(EVENT_TYPE)
