const NOTIFICATION_TYPE = {
  DOOR_LOW_BATTERY: 'DOOR_LOW_BATTERY',
  DOOR_TAMPERED: 'DOOR_TAMPERED',
  DOOR_INACTIVITY: 'DOOR_INACTIVITY',
  DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED',
  DEVICE_DISCONNECTED_REMINDER: 'DEVICE_DISCONNECTED_REMINDER',
  DOOR_DISCONNECTED: 'DOOR_DISCONNECTED',
  DOOR_DISCONNECTED_REMINDER: 'DOOR_DISCONNECTED_REMINDER',
  DEVICE_RECONNECTED: 'DEVICE_RECONNECTED',
  DOOR_RECONNECTED: 'DOOR_RECONNECTED',
}

module.exports = Object.freeze(NOTIFICATION_TYPE)
