/*
 * sensorEvents.js
 *
 * Handles all types of events generated by sensors via particle webhooks at /api/sensorEvent
 */

// Third-party dependencies
const Validator = require('express-validator')

// In-house dependencies
const { helpers, twilioHelpers } = require('./utils/index')
const { EVENT_TYPE } = require('./enums/index')
const db_new = require('./db/db_new')

const particleWebhookAPIKey = helpers.getEnvVar('PARTICLE_WEBHOOK_API_KEY')
const STILLNESS_ALERT_REMINDER = helpers.getEnvVar('STILLNESS_ALERT_REMINDER')

// ----------------------------------------------------------------------------------------------------------------------------

async function scheduleStillnessAlerts(client, device, sessionId) {
  const reminderTimeout = STILLNESS_ALERT_REMINDER * 60 * 1000

  async function handleStillnessReminder(reminderNumber) {
    try {
      const messageKey = reminderNumber === 1 ? 'stillnessAlertFirstReminder' : 'stillnessAlertSecondReminder'
      const textMessage = helpers.translateMessageKeyToMessage(messageKey, { client, device })
      await db_new.createEvent(sessionId, EVENT_TYPE.STILLNESS_ALERT, messageKey)
      await twilioHelpers.sendMessageToPhoneNumbers(device.deviceTwilioNumber, client.responderPhoneNumbers, textMessage)
    } catch (error) {
      helpers.logError(`Error in stillness reminder ${reminderNumber}: ${error.message}`)
    }
  }

  async function handleStillnessFallback() {
    try {
      const messageKey = 'stillnessAlertFallback'
      const textMessage = helpers.translateMessageKeyToMessage(messageKey, { client, device })
      await db_new.createEvent(sessionId, EVENT_TYPE.STILLNESS_ALERT, messageKey)
      await twilioHelpers.sendMessageToPhoneNumbers(device.deviceTwilioNumber, client.fallbackPhoneNumbers, textMessage)
    } catch (error) {
      helpers.logError(`Error in fallback alert: ${error.message}`)
    }
  }

  const alertSequence = [
    {
      handler: () => handleStillnessReminder(1),
      delay: reminderTimeout,
    },
    {
      handler: () => handleStillnessReminder(2),
      delay: reminderTimeout * 2,
    },
    {
      handler: () => handleStillnessFallback(),
      delay: reminderTimeout * 3,
    },
  ]

  for (const alert of alertSequence) {
    setTimeout(async () => {
      try {
        const currentSession = await db_new.getLatestActiveSessionWithDeviceId(device.deviceId)
        if (
          currentSession &&
          currentSession.sessionId === sessionId &&
          !currentSession.doorOpened &&
          (!currentSession.attendingResponderNumber ||
            (currentSession.attendingResponderNumber && currentSession.selectedSurveyCategory === 'Occupant Okay'))
        ) {
          await alert.handler()
        }
      } catch (error) {
        helpers.logError(`scheduleStillnessAlerts: ${error.message}`)
      }
    }, alert.delay)
  }
}

// ----------------------------------------------------------------------------------------------------------------------------

function selectMessageKeyForNewSession(eventType) {
  switch (eventType) {
    case EVENT_TYPE.DURATION_ALERT:
      return 'durationAlert'
    case EVENT_TYPE.STILLNESS_ALERT:
      return 'stillnessAlert'
    default: {
      throw new Error(`selectMessageKeyForNewSession: Invalid event type received as the first alert: ${eventType}`)
    }
  }
}

async function selectMessageKeyForExistingSession(eventType, currentSession, pgClient) {
  try {
    switch (eventType) {
      case EVENT_TYPE.DURATION_ALERT:
        return 'durationAlert'
      case EVENT_TYPE.STILLNESS_ALERT:
        return 'stillnessAlert'
      case EVENT_TYPE.DOOR_OPENED: {
        const latestAlertEvent = await db_new.getLatestAlertEvent(currentSession.sessionId, pgClient)
        if (!latestAlertEvent) {
          throw new Error(`No latest alert event found for session ID: ${currentSession.sessionId}`)
        }

        switch (latestAlertEvent.eventType) {
          case EVENT_TYPE.DURATION_ALERT:
            return 'durationAlertSurveyPromptDoorOpened'
          case EVENT_TYPE.STILLNESS_ALERT:
            return 'stillnessAlertSurveyDoorOpened'
          default: {
            throw new Error(`Invalid latest alert event type: ${latestAlertEvent.eventType}`)
          }
        }
      }
      default: {
        throw new Error(`Invalid event type: ${eventType}`)
      }
    }
  } catch (error) {
    throw new Error(`selectMessageKeyForExistingSession: ${error.message}`)
  }
}

// ----------------------------------------------------------------------------------------------------------------------------

async function handleNewSession(client, device, eventType, eventData, pgClient) {
  try {
    const messageKey = selectMessageKeyForNewSession(eventType)
    const textMessage = helpers.translateMessageKeyToMessage(messageKey, {
      client,
      device,
      params: { occupancyDuration: eventData.occupancyDuration },
    })

    // create a new active session
    const newSession = await db_new.createSession(device.deviceId, pgClient)
    if (!newSession) {
      throw new Error(`Failed to create a new session`)
    }

    // log the event and send the message to all responders
    await db_new.createEvent(newSession.sessionId, eventType, messageKey, pgClient)
    await twilioHelpers.sendMessageToPhoneNumbers(device.deviceTwilioNumber, client.responderPhoneNumbers, textMessage)

    // schedule the stillness alerts (these don't use the current transaction)
    if (eventType === EVENT_TYPE.STILLNESS_ALERT) {
      scheduleStillnessAlerts(client, device, newSession.sessionId)
    }
  } catch (error) {
    throw new Error(`handleNewSession: Error handling new session for device ID: ${device.deviceId} - ${error.message}`)
  }
}

async function handleExistingSession(client, device, eventType, eventData, currentSession, pgClient) {
  // if an alert is published to an existing active session after the door was opened
  // it means that the alert was triggered by a different occupant afterwards
  // in that case, discard the session and create a new one
  if (currentSession.doorOpened) {
    helpers.log(`Received sensor event for an existing session after door opened, creating new session`)
    await handleNewSession(client, device, eventType, eventData, pgClient)
    return
  }

  try {
    const messageKey = await selectMessageKeyForExistingSession(eventType, currentSession, pgClient)
    const textMessage = helpers.translateMessageKeyToMessage(messageKey, {
      client,
      device,
      params: { occupancyDuration: eventData.occupancyDuration },
    })

    // Update session when door is opened
    if (eventType === EVENT_TYPE.DOOR_OPENED) {
      const newDoorOpened = true
      let newSurveySent = currentSession.surveySent

      // If this is a stillness alert survey door open event, also mark survey as sent
      if (messageKey === 'stillnessAlertSurveyDoorOpened') {
        newSurveySent = true
      }

      await db_new.updateSession(currentSession.sessionId, currentSession.sessionStatus, newDoorOpened, newSurveySent, pgClient)
    }

    // if the survey was already sent and door is opened, don't send anything
    if (eventType === EVENT_TYPE.DOOR_OPENED && currentSession.surveySent) {
      return
    }
    // If survey was sent and selected category is 'Occupant Okay', send the message to only the attending responder
    // otherwise send message to all the responders
    if (currentSession.attendingResponderNumber && currentSession.surveySent && currentSession.selectedSurveyCategory === 'Occupant Okay') {
      await db_new.createEvent(currentSession.sessionId, EVENT_TYPE.MSG_SENT, messageKey, pgClient)
      await twilioHelpers.sendMessageToPhoneNumbers(device.deviceTwilioNumber, currentSession.attendingResponderNumber, textMessage)
    } else {
      await db_new.createEvent(currentSession.sessionId, eventType, messageKey, pgClient)
      await twilioHelpers.sendMessageToPhoneNumbers(device.deviceTwilioNumber, client.responderPhoneNumbers, textMessage)
    }

    // schedule the stillness alerts (these don't use the current transaction)
    if (eventType === EVENT_TYPE.STILLNESS_ALERT) {
      scheduleStillnessAlerts(client, device, currentSession.sessionId)
    }
  } catch (error) {
    throw new Error(`handleExistingSession: Error handling existing session with session ID ${currentSession.sessionId}: ${error.message}`)
  }
}

async function processSensorEvent(client, device, eventType, eventData) {
  let pgClient

  try {
    pgClient = await db_new.beginTransaction()
    if (!pgClient) {
      throw new Error('Error starting transaction')
    }

    // A sensor cannot send more than one stillnessAlert
    if (eventData.numStillnessAlertsSent > 1) {
      throw new Error(`More than one stillness alert received for device: ${device.deviceId}`)
    }

    // A session is finished only if its session_status is COMPLETED and door_opened is true.
    // Ever other session is considered as an "active" session and should be selected here.
    // Those are (status, doorOpened) --> (ACTIVE, true), (ACTIVE, false), (COMPLETED, false)
    const currentSession = await db_new.getLatestActiveSessionWithDeviceId(device.deviceId, pgClient)
    if (!currentSession) {
      await handleNewSession(client, device, eventType, eventData, pgClient)
    } else {
      await handleExistingSession(client, device, eventType, eventData, currentSession, pgClient)
    }

    await db_new.commitTransaction(pgClient)
  } catch (error) {
    if (pgClient) {
      try {
        await db_new.rollbackTransaction(pgClient)
      } catch (rollbackError) {
        throw new Error(`Error rolling back transaction: ${rollbackError}. Rollback attempted because of error: ${error}`)
      }
    }
    throw new Error(`processSensorEvent: ${error.message}`)
  }
}

// ----------------------------------------------------------------------------------------------------------------------------
// Sensor Events (/api/sensorEvent)

const validateSensorEvent = [
  Validator.body('event')
    .exists()
    .isString()
    .custom(value => {
      const validEvents = ['Duration Alert', 'Stillness Alert', 'Door Opened']
      return validEvents.includes(value)
    }),
  Validator.body('data').exists().isString(),
  Validator.body('coreid').exists().isString(),
  Validator.body('api_key').exists().isString(),
]

function parseSensorEventType(receivedEventType) {
  const eventTypeMapping = {
    'Duration Alert': EVENT_TYPE.DURATION_ALERT,
    'Stillness Alert': EVENT_TYPE.STILLNESS_ALERT,
    'Door Opened': EVENT_TYPE.DOOR_OPENED,
  }
  const eventType = eventTypeMapping[receivedEventType]
  if (!eventType) throw new Error(`Unknown event type: ${receivedEventType}`)
  return eventType
}

function parseSensorEventData(receivedEventData) {
  const eventData = typeof receivedEventData === 'string' ? JSON.parse(receivedEventData) : receivedEventData
  if (!eventData) throw new Error('Error parsing event data')

  const requiredFields = {
    alertSentFromState: 'number',
    numDurationAlertsSent: 'number',
    numStillnessAlertsSent: 'number',
    occupancyDuration: 'number',
  }

  for (const [field] of Object.entries(requiredFields)) {
    if (!(field in eventData)) {
      throw new Error(`Missing required field: ${field}`)
    }
    if (typeof eventData[field] !== 'number') {
      throw new Error(`Invalid type for ${field}: expected number, got ${typeof eventData[field]}`)
    }
  }

  return eventData
}

async function handleSensorEvent(request, response) {
  try {
    const validationErrors = Validator.validationResult(request).formatWith(helpers.formatExpressValidationErrors)
    if (!validationErrors.isEmpty()) {
      throw new Error(`Bad request: ${validationErrors.array()}`)
    }

    const { api_key, event: receivedEventType, data: receivedEventData, coreid: particleDeviceID } = request.body
    if (api_key !== particleWebhookAPIKey) throw new Error('Access not allowed: Invalid API key')

    const eventType = parseSensorEventType(receivedEventType)
    const eventData = parseSensorEventData(receivedEventData)

    const device = await db_new.getDeviceWithParticleDeviceId(particleDeviceID)
    if (!device) throw new Error(`No device matches the coreID: ${particleDeviceID}`)

    const client = await db_new.getClientWithClientId(device.clientId)
    if (!client) throw new Error(`No client found for device: ${device.deviceId}`)

    if (client.devicesSendingAlerts && device.isSendingAlerts) {
      await processSensorEvent(client, device, eventType, eventData)
    }

    response.status(200).json('OK')
  } catch (error) {
    helpers.logError(`Error on ${request.path}: ${error.message}`)
    // Must send 200 so as not to be throttled by Particle
    response.status(200).json(error.message)
  }
}

// ----------------------------------------------------------------------------------------------------------------------------

module.exports = {
  validateSensorEvent,
  handleSensorEvent,
}
