name: Run Server Tests

run-name: Running Server Tests for ${{ github.ref }}

on: [push]

env:
  PG_USER: brave
  PG_USER_TEST: brave
  PG_DATABASE: brave
  PG_DATABASE_TEST: brave
  PG_PASSWORD: actionspassword
  PG_PASSWORD_TEST: actionspassword
  PG_PORT: 5432
  PG_PORT_TEST: 5432
  PG_HOST: localhost
  PG_HOST_TEST: localhost
  WEB_USERNAME_TEST: ActionsDashboardUsername
  PASSWORD_TEST: ActionsDashboardPassword
  SECRET_TEST: ActionsCookieSecret
  SESSION_RESET_THRESHOLD_TEST: 2000
  SESSION_NUMBER_OF_ALERTS_TO_ACCEPT_RESET_REQUEST_TEST: 4
  PARTICLE_PRODUCT_GROUP_TEST: product-123
  LOW_BATTERY_ALERT_TIMEOUT_TEST: 2
  MAX_STILLNESS_ALERTS_TEST: 2
  INTERVAL_TO_CHECK_ALERTS_TEST: 60
  SUBSEQUENT_VITALS_ALERT_THRESHOLD_TEST: 2
  PA_API_KEY_PRIMARY_TEST: primaryPAkey
  PA_API_KEY_SECONDARY_TEST: secondaryPAkey
  PA_CLIENT_ID_TEST: fakeclientid.apps.googleusercontent.com
  PA_CLIENT_SECRET_TEST: fakeclientsecret
  PARTICLE_WEBHOOK_API_KEY_TEST: webhookKey

jobs:
  ServerTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm --prefix server ci
      - run: npm --prefix server run lint
      - run: npm --prefix server run test
